---
version: 1
language: PHP
dockerfile: docker/Dockerfile
code: /code
workdir: /code/%day%
cmd: php /code/%day%/run.php
environment:
 - TIMED=1
daypath: "%day%"
inputfile: "%day%/input.txt"
answerfile: "%day%/answers.txt"
common:
 - common
